version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 5

  admin-service:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ./:/app
      - ./config.json:/app/config.json
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python /app/admin_service/service.py

  call-service:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ./:/app
      - ./config.json:/app/config.json
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python /app/call_service/service.py

  lead-service:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ./:/app
      - ./config.json:/app/config.json
    ports:
      - "8002:8002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python /app/lead_service/service.py

  orchestrator-service:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ./:/app
      - ./config.json:/app/config.json
    ports:
      - "8003:8003"
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python /app/orchestrator_service/service.py

  notification-service:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ./:/app
      - ./config.json:/app/config.json
    ports:
      - "8004:8004"
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python /app/notification_service/service.py 