from setuptools import setup, find_packages

setup(
    name="rc_zoho_microservices",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.95.0,<1.0.0",
        "uvicorn>=0.21.0,<1.0.0",
        "httpx>=0.24.0,<1.0.0",
        "pydantic>=1.10.7,<2.0.0",
        "jinja2>=3.1.2,<4.0.0",
        "python-multipart>=0.0.6,<1.0.0",
        "email-validator>=2.0.0,<3.0.0",
        "cryptography>=41.0.0,<42.0.0",
        "python-dotenv>=1.0.0,<2.0.0",
        "aiokafka>=0.8.0,<1.0.0",
        "aio-pika>=9.0.0,<10.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.3.1,<8.0.0",
            "pytest-asyncio>=0.21.0,<1.0.0",
            "black>=23.3.0,<24.0.0",
            "isort>=5.12.0,<6.0.0",
            "mypy>=1.2.0,<2.0.0",
            "flake8>=6.0.0,<7.0.0",
        ],
    },
    author="RingCentral-Zoho Integration Team",
    author_email="example@example.com",
    description="Microservices-based integration between RingCentral and Zoho CRM",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/example/rc_zoho_microservices",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.9",
)