apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-service
  labels:
    app: call-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-service
  template:
    metadata:
      labels:
        app: call-service
    spec:
      containers:
      - name: call-service
        image: rc-zoho-microservices:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "rc_zoho_microservices.call_service.service"]
        ports:
        - containerPort: 8001
        env:
        - name: MESSAGE_BROKER_TYPE
          value: "rabbitmq"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: password
        - name: CALL_SERVICE_HOST
          value: "0.0.0.0"
        - name: CALL_SERVICE_PORT
          value: "8001"
        - name: RC_JWT_TOKEN
          valueFrom:
            secretKeyRef:
              name: ringcentral-credentials
              key: jwt_token
        - name: RC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ringcentral-credentials
              key: client_id
        - name: RC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ringcentral-credentials
              key: client_secret
        - name: RC_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: ringcentral-credentials
              key: account_id
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: rc-zoho-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: rc-zoho-data-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: rc-zoho-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: call-service
spec:
  selector:
    app: call-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP